// Set the initial point value to zero
console.log('JS connected')
var points = 0;

// Write a function that generates a random number
function randomNumber(min, max) {
  var interval = Math.random() * (max - min) + min;
  return Math.floor(interval);
}
// This function will respond to the users mouseclick on the appearing item
// and will cause the item to shrink back to height 0 (disappearing in the
// eues of the user)

// I will also try to update the points live at the top of the screen
function catchMe(event) {
  console.log('BOO');
  $(event.target).css({
    height: '0px',
  })
  $('.flex-container').css({
    height: '50px',
  })
  points += 100;
}

// I keep this open to the entire body since the items will be located at
// different parts of the screen
$('.creature').click(catchMe)


// write a function that makes a div appear in the a window
// the initial height of this div is 0 so it already exists, it is
// just growing through this animation
function grow(div) {
  $(div).animate({
    height: '50px',
    width: '50px',
  }, 500);
  // The shrink function will cause the height to shrink back to 0,
  // making it appear as if the div has disappeared. The setTimeout
  // will make it shrink after appearing for a set number of seconds
  // which will decrease in the next level
  setTimeout( function() {shrink(div); }, 2000);
}

// write a function that makes a div shrink and disappear
function shrink(div) {
  $(div).animate({
    height: '0px',
  })
}

// have a setInterval function that continues to call the appear function
// The randomNumber will be generated by the function above and will switch
// up how frequently the divs appear in the windows

// Setting setInterval methods to a variable will allow us to clear the inerval
// when the time is up.
var window1 = setInterval(function() { grow('#one'); }, randomNumber(4000, 10000));
var window2 = setInterval(function() { grow('#two'); }, randomNumber(4000, 10000));
var window3 = setInterval(function() { grow('#three'); }, randomNumber(4000, 10000));
var window4 = setInterval(function() { grow('#four'); }, randomNumber(4000, 10000));
var window5 = setInterval(function() { grow('#five'); }, randomNumber(4000, 10000));
var window6 = setInterval(function() { grow('#six'); }, randomNumber(4000, 10000));
var window7 = setInterval(function() { grow('#seven'); }, randomNumber(4000, 10000));
var window8 = setInterval(function() { grow('#eight'); }, randomNumber(4000, 10000));
var window9= setInterval(function() { grow('#nine'); }, randomNumber(4000, 10000));
var window10 = setInterval(function() { grow('#ten'); }, randomNumber(4000, 10000));
var window11 = setInterval(function() { grow('#eleven'); }, randomNumber(4000, 10000));

// Create a timer using a loop
// Tictoc will add seconds to clock
var seconds = 45;
var timer = null;

function tictoc(){
  seconds -= 1;
  console.log(seconds);
  if (seconds === 0) {
    clearInterval(window1);
    clearInterval(window2);
    clearInterval(window3);
    clearInterval(window4);
    clearInterval(window5);
    clearInterval(window6);
    clearInterval(window7);
    clearInterval(window8);
    clearInterval(window9);
    clearInterval(window10);
    clearInterval(window11);
  }
}

// The set interval will ensure that tictoc is only adding seconds
// to the clock after every second
function startTime() {
  timer = setInterval(tictoc, 1000)
}

// Document.ready will start the timer when the document has loaded
// so they player has a specific amount of time to catch as many creatures
// as possible before the time is up
$(document).ready(startTime)








// function position(event) {
//   console.log('I\'m here');
//   var x = event.pageX;
//   var y = event.pageY;
//   console.log('x = ' + x + ', y = ' + y)

// }


// $('html').click(position)
